# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\"\xc3\x02\n\x07Message\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x1c\n\x04text\x18\x04 \x01(\x0b\x32\x0c.TextMessageH\x00\x12 \n\x06tensor\x18\x05 \x01(\x0b\x32\x0e.TensorMessageH\x00\x12\"\n\x0bsolve_start\x18\x06 \x01(\x0b\x32\x0b.SolveStartH\x00\x12\x1e\n\tsolve_end\x18\x07 \x01(\x0b\x32\t.SolveEndH\x00\x12*\n\x0fupdate_variable\x18\x08 \x01(\x0b\x32\x0f.UpdateVariableH\x00\x12#\n\x0c\x61\x64\x64_bab_node\x18\t \x01(\x0b\x32\x0b.AddBabNodeH\x00\x12\'\n\x0eprune_bab_node\x18\n \x01(\x0b\x32\r.PruneBabNodeH\x00\x42\t\n\x07\x63ontent\"-\n\x0bTextMessage\x12\r\n\x05level\x18\x01 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"Q\n\rTensorMessage\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0e\n\x06group_\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x03 \x01(\t\x12\r\n\x05sizes\x18\x04 \x03(\x05\"\x1c\n\nSolveStart\x12\x0e\n\x06solver\x18\x01 \x01(\t\"\x1a\n\x08SolveEnd\x12\x0e\n\x06solver\x18\x01 \x01(\t\"D\n\x0eUpdateVariable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\titeration\x18\x02 \x03(\rB\x02\x10\x01\x12\r\n\x05value\x18\x03 \x01(\x01\"\xe6\x01\n\nAddBabNode\x12\x16\n\ncoordinate\x18\x01 \x03(\rB\x02\x10\x01\x12\x13\n\x0blower_bound\x18\x02 \x01(\x01\x12\x13\n\x0bupper_bound\x18\x03 \x01(\x01\x12>\n\x15variables_information\x18\x04 \x03(\x0b\x32\x1f.AddBabNode.VariableInformation\x1aV\n\x13VariableInformation\x12\x15\n\rvariable_name\x18\x01 \x01(\t\x12\x13\n\x0blower_bound\x18\x02 \x01(\x01\x12\x13\n\x0bupper_bound\x18\x03 \x01(\x01\"&\n\x0cPruneBabNode\x12\x16\n\ncoordinate\x18\x01 \x03(\rB\x02\x10\x01\x62\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Message.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_id', full_name='Message.run_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Message.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='Message.text', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tensor', full_name='Message.tensor', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solve_start', full_name='Message.solve_start', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solve_end', full_name='Message.solve_end', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_variable', full_name='Message.update_variable', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_bab_node', full_name='Message.add_bab_node', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prune_bab_node', full_name='Message.prune_bab_node', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='Message.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=18,
  serialized_end=341,
)


_TEXTMESSAGE = _descriptor.Descriptor(
  name='TextMessage',
  full_name='TextMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='TextMessage.level', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='TextMessage.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=388,
)


_TENSORMESSAGE = _descriptor.Descriptor(
  name='TensorMessage',
  full_name='TensorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='TensorMessage.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_', full_name='TensorMessage.group_', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='TensorMessage.dataset', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sizes', full_name='TensorMessage.sizes', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=471,
)


_SOLVESTART = _descriptor.Descriptor(
  name='SolveStart',
  full_name='SolveStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='solver', full_name='SolveStart.solver', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=501,
)


_SOLVEEND = _descriptor.Descriptor(
  name='SolveEnd',
  full_name='SolveEnd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='solver', full_name='SolveEnd.solver', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=529,
)


_UPDATEVARIABLE = _descriptor.Descriptor(
  name='UpdateVariable',
  full_name='UpdateVariable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UpdateVariable.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iteration', full_name='UpdateVariable.iteration', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='UpdateVariable.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=599,
)


_ADDBABNODE_VARIABLEINFORMATION = _descriptor.Descriptor(
  name='VariableInformation',
  full_name='AddBabNode.VariableInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variable_name', full_name='AddBabNode.VariableInformation.variable_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lower_bound', full_name='AddBabNode.VariableInformation.lower_bound', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upper_bound', full_name='AddBabNode.VariableInformation.upper_bound', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=746,
  serialized_end=832,
)

_ADDBABNODE = _descriptor.Descriptor(
  name='AddBabNode',
  full_name='AddBabNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='AddBabNode.coordinate', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lower_bound', full_name='AddBabNode.lower_bound', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upper_bound', full_name='AddBabNode.upper_bound', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variables_information', full_name='AddBabNode.variables_information', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ADDBABNODE_VARIABLEINFORMATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=602,
  serialized_end=832,
)


_PRUNEBABNODE = _descriptor.Descriptor(
  name='PruneBabNode',
  full_name='PruneBabNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='PruneBabNode.coordinate', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=834,
  serialized_end=872,
)

_MESSAGE.fields_by_name['text'].message_type = _TEXTMESSAGE
_MESSAGE.fields_by_name['tensor'].message_type = _TENSORMESSAGE
_MESSAGE.fields_by_name['solve_start'].message_type = _SOLVESTART
_MESSAGE.fields_by_name['solve_end'].message_type = _SOLVEEND
_MESSAGE.fields_by_name['update_variable'].message_type = _UPDATEVARIABLE
_MESSAGE.fields_by_name['add_bab_node'].message_type = _ADDBABNODE
_MESSAGE.fields_by_name['prune_bab_node'].message_type = _PRUNEBABNODE
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['text'])
_MESSAGE.fields_by_name['text'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['tensor'])
_MESSAGE.fields_by_name['tensor'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['solve_start'])
_MESSAGE.fields_by_name['solve_start'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['solve_end'])
_MESSAGE.fields_by_name['solve_end'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['update_variable'])
_MESSAGE.fields_by_name['update_variable'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['add_bab_node'])
_MESSAGE.fields_by_name['add_bab_node'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['prune_bab_node'])
_MESSAGE.fields_by_name['prune_bab_node'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_ADDBABNODE_VARIABLEINFORMATION.containing_type = _ADDBABNODE
_ADDBABNODE.fields_by_name['variables_information'].message_type = _ADDBABNODE_VARIABLEINFORMATION
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['TextMessage'] = _TEXTMESSAGE
DESCRIPTOR.message_types_by_name['TensorMessage'] = _TENSORMESSAGE
DESCRIPTOR.message_types_by_name['SolveStart'] = _SOLVESTART
DESCRIPTOR.message_types_by_name['SolveEnd'] = _SOLVEEND
DESCRIPTOR.message_types_by_name['UpdateVariable'] = _UPDATEVARIABLE
DESCRIPTOR.message_types_by_name['AddBabNode'] = _ADDBABNODE
DESCRIPTOR.message_types_by_name['PruneBabNode'] = _PRUNEBABNODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)

TextMessage = _reflection.GeneratedProtocolMessageType('TextMessage', (_message.Message,), dict(
  DESCRIPTOR = _TEXTMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:TextMessage)
  ))
_sym_db.RegisterMessage(TextMessage)

TensorMessage = _reflection.GeneratedProtocolMessageType('TensorMessage', (_message.Message,), dict(
  DESCRIPTOR = _TENSORMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:TensorMessage)
  ))
_sym_db.RegisterMessage(TensorMessage)

SolveStart = _reflection.GeneratedProtocolMessageType('SolveStart', (_message.Message,), dict(
  DESCRIPTOR = _SOLVESTART,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:SolveStart)
  ))
_sym_db.RegisterMessage(SolveStart)

SolveEnd = _reflection.GeneratedProtocolMessageType('SolveEnd', (_message.Message,), dict(
  DESCRIPTOR = _SOLVEEND,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:SolveEnd)
  ))
_sym_db.RegisterMessage(SolveEnd)

UpdateVariable = _reflection.GeneratedProtocolMessageType('UpdateVariable', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEVARIABLE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:UpdateVariable)
  ))
_sym_db.RegisterMessage(UpdateVariable)

AddBabNode = _reflection.GeneratedProtocolMessageType('AddBabNode', (_message.Message,), dict(

  VariableInformation = _reflection.GeneratedProtocolMessageType('VariableInformation', (_message.Message,), dict(
    DESCRIPTOR = _ADDBABNODE_VARIABLEINFORMATION,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:AddBabNode.VariableInformation)
    ))
  ,
  DESCRIPTOR = _ADDBABNODE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:AddBabNode)
  ))
_sym_db.RegisterMessage(AddBabNode)
_sym_db.RegisterMessage(AddBabNode.VariableInformation)

PruneBabNode = _reflection.GeneratedProtocolMessageType('PruneBabNode', (_message.Message,), dict(
  DESCRIPTOR = _PRUNEBABNODE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:PruneBabNode)
  ))
_sym_db.RegisterMessage(PruneBabNode)


_UPDATEVARIABLE.fields_by_name['iteration']._options = None
_ADDBABNODE.fields_by_name['coordinate']._options = None
_PRUNEBABNODE.fields_by_name['coordinate']._options = None
# @@protoc_insertion_point(module_scope)
