timelimit = 86400

[cplex]

[ipopt]
tol = 1e-7

[ipopt.logging]
level = 'J_ITERSUMMARY'

[outer_approximation]
maxiter = 50
tolerance = 1e-8
relative_tolerance = 1e-8

[logging]
level = 'INFO'
stdout = true