name: test Galini

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v1
    - name: setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/cog-imperial/suspect.git
        pip install -r requirements.txt
        pip install gurobipy
        conda install ipopt --no-update-deps
    - name: Test with pytest
      run: |
        pip install -e ./
        pytest --cov=galini ./